# Generated by Django 4.0.4 on 2022-05-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picasso', '0002_image_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_description',
            new_name='image_description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_file',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_name',
            new_name='image_name',
        ),
    ]
